### ISSUE TITLE
Sporadic ECONNRESET error

### ISSUE THREAD

**Issue by dbaq** [docusign/docusign-esign-node-client#236]
Hi there,

We have been using this library to make API calls to DocuSign for a while. We are experiencing a large number of `ECONNRESET` errors when calling the `envelopesApi.getDocument` function.

```
envelopesApi.getDocument(accountId, envelopeId, documentId, (err, document) => {
```

The `err` object returns the following:

```
err: {
  host: "www.docusign.net"
  code: "ECONNRESET"
  path: null
  port: 443
}
```

Over the last 30 days, we had this error 208 times out of ~35k requests (about 0.6%). Any recommendations on what could be happening? and how we could prevent this error?

Thanks.

**Comment by EdwinMoralesDS** [comment]
Hello,

The "ECONNRESET" error is normally connect to something being blocked in the network.  I would recommend doublechecking with your network team that everything in this list is allowed: 

https://www.docusign.com/trust/security/esignature

If you're not able to identify anything being blocked, please open a case with us so we can take a closer look.  You can open a new support case on this page: support.docusign.com
