### ISSUE TITLE
Docusign iframe cookie persists

### ISSUE THREAD

**Issue by lworkman** [docusign/docusign-esign-node-client#237]
I'm making use of the different views for embedding docusign in my app (`createEditView`, for example), and I've noticed that the session cookie persists across page loads. Is that something that can be disabled?

I'm using the recommend flow (each user gets their own user in docusign) but that doesn't prevent users from returning to docusign themselves. The behaviour I'm seeing right now is:

1. Generate a new URL through the API
2. Display an iframe with the `src` set to that URL
3. User does whatever they need to do, cookie is stored in their browser
4. User navigates directly to `https://appdemo.docusign.com/home` and can use docusign outside of my app without issue.

To be clear, I want to make it so step 4 CANNOT happen.

**Comment by InbarGazit** [comment]
Hello, I feel there's some confusion here.
Are steps 1-4 all performed in the same browser/device?
The issue here is that in Step 1 you may be using Auth Code Grant and log into the browser. Then step 2/3 has no bearings here. You can jump to step 4 from step 1 and would still be logged in. The cookie is generated by the login UI that was used and is persisted, that's a core feature of the DocuSign login UI.

**Comment by lworkman** [comment]
I'm using JWT to generate a token through my API

**Comment by lworkman** [comment]
Full steps are:

1. Generate JWT for user with limited permissions
2. Use generated token THROUGH my API to generate a new view URL (`EnvelopesApi.createEditView`)
3. Open up a fresh web browser session to a page with an iframe set to the URL returned from step 2
4. Open up a second tab, navigate to https://appdemo.docusign.com/home, user is able to do stuff in the UI

**Comment by acooper4960** [comment]
I believe the confusion here is around how JWT tokens are issued. A token generated with your app would not work against other DS applications.

**Comment by lworkman** [comment]
I didn't end up going with docusign in the end, but I'm confused about how that answers my question? By other DS applications, do you mean other apps that _don't_ include the core DS app?

As a user of the API, I would expect any cookie generated for my users would only work through my API, not the core DS application.
