### ISSUE TITLE
Timeout creating an envelope

### ISSUE THREAD

**Issue by baumblatt** [docusign/docusign-esign-node-client#238]
Hello,

I'm receiving a timeout error while creating an envelope with a large html document that results in a 120 pages pdf file.

```
try {
    const {envelopeId} = await new EnvelopesApi(api).createEnvelope("token", {envelopeDefinition: envelope});
    // .... do something simple with envelopeId
} catch (error) {
     // error.toString() ==> Error: Timeout of 60000ms exceeded
}
```

The envelope was created successfully, but the client was aware of it and was unable to get the `envelopeId` to track the signature process.

Is there a way to dynamic config the timeout prior the API call?

Best reagards,
Bernardo

**Comment by acooper4960** [comment]
hey @baumblatt ApiClient.timeout is a publicly accessible property that you can set to change this behavior. https://github.com/docusign/docusign-node-client/blob/master/src/ApiClient.js#L161

**Comment by baumblatt** [comment]
Hi @acooper4960 ,

Thank you for the information, this feature, and several others, are not in typescript definition package [@types/docusign-esign](https://www.npmjs.com/package/@types/docusign-esign)

Please see the definition [here](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/docusign-esign)!

Looking forward for a better support of typescript by DocuSign.

Best reagards.
