### ISSUE TITLE
What is the correct way to void envelopes?

### ISSUE THREAD

**Issue by yharrison-tl** [docusign/docusign-esign-node-client#246]
I tried to void envelopes with the following code provided on this [blog post](https://www.docusign.com/blog/dsdev-common-api-tasks-void-an-envelope).

```javascript
let envelope = new docusign.Envelope()
envelope.status = 'voided'
envelope.voidedReason = reason
await this.envelopeApi.update(this.accountId, envelopeUUID, envelope)
```
The code always runs without errors but after I retrieve the current envelope status from the API the state never changes to voided.

Then I changed the .update call as specified here on the [api docs](http://docusign.github.io/docusign-node-client/module-api_EnvelopesApi.html#update)
```javascript
await this.envelopeApi.update(this.accountId, envelopeUUID, { envelope })
```
This way it errors out the following
```json
{"errorCode":"INVALID_REQUEST_PARAMETER","message":"The request contained at least one invalid parameter. Value for 'voidedReason' must be specified when voiding an envelope."}
```

FYI:
* `this.envelopeApi` is working fine for retrieve and for envelope creation

**Comment by acooper4960** [comment]
hi @yharrison-tl 
I have just ran the following as was able to successfully void the envelope:

`var envelope = new docusign.Envelope();
        envelope.status = 'voided';
        envelope.voidedReason = 'I am voiding this  because reason';
        envelopesApi.update(accountId, 'xxxxxxx-xxxxx-xxxx-xxxx-xxxxxxxx', { envelope: envelope })
          .then((data) => {
            console.log(data);
            envelopesApi.getEnvelope(accountId, 'xxxxxxx-xxxxx-xxxx-xxxx-xxxxxxxx')
              .then(envelope => {
              console.log(envelope);
              //console.log(err);
            })
          }).catch(err => {
            console.log('error')
            console.log(err)
        });
`
Could you verify that reason is a string and not null, as well as your SDK version?

**Comment by yharrison-tl** [comment]
Now it works. Probably the package was outdated.
Thank you.
