### ISSUE TITLE
Help me in getting started, how to use this NPM Module, Doc link is broken and talking about example app 

### ISSUE THREAD

**Issue by tkssharma** [docusign/docusign-esign-node-client#251]
### Problem 
I am trying to figure out how to initialize this SDK or npm module with all configuration I am having 

1. this docs link on this README.md is broken 
2. this repo talk about another example repo which is just a copy or clone 

Can you please help me on how should I start my Integration with the existing node js app after adding this npm module?

Currently, i have Node JS APIs with react app running on client-side

**Comment by acooper4960** [comment]
hey @tkssharma see https://github.com/docusign/docusign-esign-node-client/issues/248 for the location to the SDK Docs. If its your first time, you should check out our NodeJS [Quickstart](https://developers.docusign.com/docs/esign-rest-api/quickstart/). This will create a node project for you with this SDK and provide you working example of the various esign rest api methods
