### ISSUE TITLE
BulkEnvelopes api is not exported

### ISSUE THREAD

**Issue by indrapranesh** [docusign/docusign-esign-node-client#261]
BulkEnvelopes API is not exported in the index.js file of the latest version npm vesrsion of **docusign-esign**. I see the source of the BulkEnvelopes API in the repository, but it is not exported in the latest version.

docusign-esign NPM version : 4.13.0

I couldn't use the BulkEnvelopes API, The exports are added in the master branch of the repo, but in the npm it is not there ?
How do I overcome this issue ?

**Comment by jaebradley** [comment]
@indrapranesh I'm not affiliated with this repository or docusign, but here's what I found that hopefully answers your question.

There's [a branch called `4.13.0-v2-21.2.00.00`](https://github.com/docusign/docusign-esign-node-client/tree/4.13.0-v2-21.2.00.00).

If you take a look at [the `index.js` file in this branch](https://github.com/docusign/docusign-esign-node-client/blob/6fcff8aa152c2cd6772049b81b6bd53c51f1dd88/src/index.js) you'll notice that there is no export called `BulkEnvelopes`.

In fact, if you introspect the exports in the package (for `4.13.0`), you'll see that only two of the exports start with the string `BulkEnvelope`.

```javascript
Object
  .entries(require('docusign-esign'))
  .filter(([key, value]) => key.startsWith('BulkEnvelope'))
  .forEach(([key, value]) => console.log(key))
```

produces

```
BulkEnvelope
BulkEnvelopeStatus
```

Looks like you'll have to use a more recent version of the library that includes that export.

**Comment by HobbyProjects** [comment]
Please use the latest npm package. It should be supported there.
