### ISSUE TITLE
ENOTFOUND error on VPN

### ISSUE THREAD

**Issue by rajkadecha** [docusign/docusign-esign-node-client#270]
I've tried latest 5.11.0 NPM but there is no proxy added. v5.1.0-Proxy branch has implemented proxy but NPM version 5.1.0 does not have proxy implementation in NPM.

Please share which version will helpful for using in VPN.

getting ENOTFOUND error for hostname account-d.docusign.com

**Comment by HobbyProjects** [comment]
VPN support is currently not there but will be included in a future release (no eta at this point). You may perhaps use the branch directly and create the package for yourself for now.
