### ISSUE TITLE
Why does my iframe sometimes initially load the Return URL page before the DocuSign form has been signed?

### ISSUE THREAD

**Issue by lilfrootyloops** [docusign/docusign-esign-node-client#278]
For my Next.js application, I'm embedding a DocuSign form using an iframe. At times when I visit the page where that form exists, I'll sometimes see the Return URL page (which I should only be redirected to in the iframe after having signed the form) when the page initially loads. After a few seconds, the correct page with the form loads in the iframe.

This issue does not occur when first visiting the form page. This typically happens after I return to home page (or visit any other page) without having signed the form and then return to the form page. Has anyone else who worked with embedding DocuSign forms using an iframe experienced this issue? If so, could you please explain how you were able to resolve it?

**Comment by kamran-bhatti** [comment]
HI, 

it's generally discouraged to use iframes for a variety of reasons when trying to do an embedded signing experience. 

This has been discussed with alternatives : 

https://www.docusign.com/blog/developers/the-problems-iframes
