### ISSUE TITLE
Formidable vulnerability

### ISSUE THREAD

**Issue by MaksimGladki** [docusign/docusign-esign-node-client#294]
Hi there!
There is a **Critical** vulnerability found in Snyk [here](https://security.snyk.io/vuln/SNYK-JS-FORMIDABLE-2838956).
It is about `formidable` library. It needs an upgrade to `3.2.4` version.
Are there any updates on this?

**Comment by acooper4960** [comment]
hello @MaksimGladki, thank you for reaching out to us about this. We are currently waiting for action on behalf of the folks who own superagent. https://github.com/visionmedia/superagent/issues/1725

**Comment by acooper4960** [comment]
This vulnerability has been officially revoked by Snyk
