### ISSUE TITLE
How to set document to updateDocument?

### ISSUE THREAD

**Issue by Lorenzras** [docusign/docusign-esign-node-client#300]
What is the correct way to set base64 string in updateDocument? 

From the documentation it only accepts 3 required parameters, (account id, envelope id, document id) 

Here is my code. 

```
import {EnvelopesApi} from 'docusign-esign';
import {apiClient} from '../../config';

export const updateDocument = async (
  accountId: string,
  envelopeId: string,
  documentId = '1',
  document: string, // base64
) => {
  const envApi = new EnvelopesApi(apiClient);

  return await envApi.updateDocument(
    accountId,
    envelopeId,
    documentId,
  );
};
```

**Comment by karankaushik95** [comment]
Based on [this](https://developers.docusign.com/docs/esign-rest-api/reference/envelopes/envelopedocuments/update/), the body would need to be a binary octet stream of the file

**Comment by Lorenzras** [comment]
> Based on [this](https://developers.docusign.com/docs/esign-rest-api/reference/envelopes/envelopedocuments/update/), the body would need to be a binary octet stream of the file

Thanks. 

Still, I don't know where to set it using nodeJS sdk. 

https://docusign.github.io/docusign-esign-node-client/module-api_EnvelopesApi.html#updateDocument

**Comment by acooper4960** [comment]
Hello @Lorenzras could I direct you to the updateList method. You will find a the `envelopeDefinition` parameter available to you to upload documents. 
https://docusign.github.io/docusign-esign-node-client/module-api_EnvelopesApi.html#updateDocuments

**Comment by Lorenzras** [comment]
> Hello @Lorenzras could I direct you to the updateEnvelopes method. You will find a the `envelopeDefinition` parameter available to you to upload documents. https://docusign.github.io/docusign-esign-node-client/module-api_EnvelopesApi.html#updateDocuments

Thanks! I'll take note of this. Turned out that there are frequent updates needed, so we just generate the documents on our server until finalized for docusigning.
