### ISSUE TITLE
Unable fetch access token, keep getting Bad request 400 

### ISSUE THREAD

**Issue by jameszhan02** [docusign/docusign-esign-node-client#302]
```javascript
const docusign = require("docusign-esign");
const fs = require("fs");
const dayjs = require("dayjs"); // Used to set and determine a token's expiration date
const express = require('express');

rsaKey = fs.readFileSync("./private.key");
const jwtLifeSec = 10 * 60;
const scopes = "signature";

const oAuth = docusign.ApiClient.OAuth;
const restApi = docusign.ApiClient.RestApi;

const basePath = restApi.BasePath.DEMO; // https://demo.docusign.net/restapi
const oAuthBasePath = oAuth.BasePath.DEMO; // account-d.docusign.com

const INTEGRATION_KEY = "*************-***********-**********";
const USER_ID = "*************-***********-**********";
// water fall demo code

const getToken = async () => {
  // Get API client and set the base paths
  try {
    const eSignApi = new docusign.ApiClient({basePath, oAuthBasePath});
    // eSignApi.setOAuthBasePath(oAuthBasePath);

    // Request a JWT token
    let results;

    results = await eSignApi.requestJWTUserToken(
      INTEGRATION_KEY,
      USER_ID,
      scopes,
      rsaKey,
      jwtLifeSec
    );
// =====================  I except getting access token inside results ======================

    return results;
  } catch (err) {
    console.log("SMTH WENT WRONG ", err);
  }
};
```

Not Sure what else I need to do here except config RSA, user id and integration key

Here is the Error message i keep get
```
Error: cannot POST /oauth/token (400)
        at Response.toError (D:\Github_repos\docusign_demo\node_modules\superagent\lib\node\response.js:94:15)
        at ResponseBase._setStatusProperties (D:\Github_repos\docusign_demo\node_modules\superagent\lib\response-base.js:123:16)
```

**Comment by karankaushik95** [comment]
It's not easily apparent what could be the issue. You can create a case with [DocuSign Developer Support](https://developers.docusign.com/support/) to help troubleshoot this further

**Comment by jameszhan02** [comment]
> 
      status: 400,
      text: '{"error":"invalid_grant","error_description":"issuer_not_found"}',
      method: 'POST',
      path: '/oauth/token'


thank you for reply. now finally i am getting smth new, this might be easier to see where is the problem i guess

**Comment by karankaushik95** [comment]
Yeah this is easier to understand. The issuer = the integration key. If your integration key looks correct, confirm that you are querying account-d.docusign.com (and not account.docusign.com)

**Comment by karankaushik95** [comment]
Also noticed that you are missing the impersonation scope (which is necessary for JWT)

**Comment by jameszhan02** [comment]
> Also noticed that you are missing the impersonation scope (which is necessary for JWT). If you add this scope, you would have to run the consent process again before going for the token

How do I implement that, if u dont mind. I am bit lost in those docs

**Comment by AsadullahMaliyawala** [comment]
@jameszhan02 hi can you please help me how you fix that i am using the same method and same error is coming.
