### ISSUE TITLE
DocuSign templating and embedded signing support for XFA PDF

### ISSUE THREAD

**Issue by trongr** [docusign/docusign-esign-node-client#310]
Does anyone know if DocuSign supports templating and embedded signing for PDF's containing XFA (https://en.wikipedia.org/wiki/XFA)? Example PDF that we would use as a template in HelloSign: https://www.canada.ca/content/dam/ircc/migration/ircc/english/pdf/kits/forms/imm5707e.pdf. Thanks!

**Comment by AbdulrahmanGameel** [comment]
Docusign does not accept Dynamic XFA PDFs
