### ISSUE TITLE
jsonwebtoken Version has high vulnerabilities in docusign-click

### ISSUE THREAD

**Issue by arealesramirez** [docusign/docusign-esign-node-client#317]
Hi Docusign,

I currently have docusign-click version 1.0.0. Currently, I'm getting vulnerabilities after running an audit (`yarn audit`) on the packages installed on my project.
![Screen Shot 2023-01-09 at 11 18 43 AM](https://user-images.githubusercontent.com/20869583/211368250-c7b8ca31-13ad-465a-9715-009270425185.png)

The solution is to upgrade `jsonwebtoken` to version `9.0.0`.

My temporary solution is to manually update the docusign-click dependency versions directly in the yarn.lock file and then run `yarn` to reinstall packages.
![Screen Shot 2023-01-09 at 11 21 17 AM](https://user-images.githubusercontent.com/20869583/211368684-c933af7d-d995-4b7a-afb0-dcfa6eff709b.png)

Ideally, docusign-click should update `jsonwebtoken` and release a new version.

Thanks in advance!

**Comment by XiaoSunXS** [comment]
+1 on this :)

**Comment by kamran-DS** [comment]
Thanks for your note. We have opened up an Engineering fix for this. 

For your reference it is DCM-8728.

**Comment by arealesramirez** [comment]
@kamran-DS Is there a good place where I can keep track of the progress made on DCM-8728?

On the other hand, I appreciate the quick response and action toward getting this issue resolved.

**Comment by acooper4960** [comment]
Hi folks, this patch is being applied to our public node SDKs this week. It is a breaking change and will require you to upgrade to the next major version. 
For esign this will be version 6.0.0

**Comment by acooper4960** [comment]
https://github.com/docusign/docusign-esign-node-client/releases/tag/v6.0.0
