### ISSUE TITLE
API error

### ISSUE THREAD

**Issue by Seamus1989** [docusign/docusign-esign-node-client#328]
Sorry but there is no way you won API awards. Nightmare to use. Docs === zero help.

**Comment by larrykluger** [comment]
I'm sorry that you had a tough experience. Can you say a little more about the difficulty? What were you trying to do? Was the quick start Node.j example of help? How could it be improved? 

Same for the docs, what was missing? Or other issues with the docs? 

Did you watch any of the videos? 
Thank you, Larry
