### ISSUE TITLE
numberTabs not returned in signer.Tabs

### ISSUE THREAD

**Issue by gloriabern1** [docusign/docusign-esign-node-client#337]
The number tab is not returned as part of the list of tabs added in a document template. Other tab fields such as text and checkbox tab are being returned. But number tab is not returned, even though I added in the document. is this a known issue?

**Comment by karankaushik95** [comment]
I just tried it out and it is being returned, although the object for it is called "numericalTabs". If you don't see this in your response, please open a support case with Developer Support and we can assist you.

**Comment by sonawane-sanket** [comment]
Thanks, @karankaushik95, for stepping in!

@gloriabern1,

Could you please confirm if you're still experiencing any issues, or has it been resolved? We're here to assist further if needed.

**Comment by sonawane-sanket** [comment]
Closing this issue for now. Feel free to reopen it if the problem persists.
