### ISSUE TITLE
EnvelopesAPI: getDocument() returning "undefined" at beginning

### ISSUE THREAD

**Issue by haileybongo** [docusign/docusign-esign-node-client#356]
Overview: 
When calling the getDocument function from the envelopes api, the base64 that is returned is prepended with "undefined".

```
await envelopesApi.getDocument(
      accountId,
      envelopeId,
      documentId
    )
```

results in

`undefinedJVBERi0xLjcKJfv8/f4KNDcgMCBvYmoKPDwvTGVuZ3RoIDQ+PnN0cmVhbQoKIHEgCmVuZHN0cmVhbQplbmRvYmoKNDggMCBvYmoKPDwvRmlsdGVyL0ZsYXRlRGVjb2RlL0xlbmd0aCA4MjI+PnN0cmVhbQpIiayXa2+...`

Current workaround:

To get this to work, I am currently removing the "undefined" from the result string. This should be fixed on the envelopesAPI side.

**Comment by sonawane-sanket** [comment]
@haileybongo 

We have released new version [7.0.2](https://www.npmjs.com/package/docusign-esign/v/7.0.2?activeTab=versions) to address the issue. Please upgrade to same and if issue still persist, let us know here
