### ISSUE TITLE
getUserInfo access token gets overwritten by the default headers, if set

### ISSUE THREAD

**Issue by joaomvfsantos** [docusign/docusign-esign-node-client#359]
The `getUserInfo` requires an `accessToken` as first parameter. This access token should always be used independent of what is set on the `defaultHeaders` variable. However regarding this bit of code:

https://github.com/docusign/docusign-esign-node-client/blob/429c5226482cec3bbd74c83452ccba91874eb19f/src/ApiClient.js#L949-L954

The specified input accessToken will be overwriten by the one in the defaultHeaders due to the spread operator.

So, as soon as you call any method that changes the defaultHeaders like `addDefaultHeader('Authorization', 'Bearer xxx')` it does not matter what you pass into the  `getUserInfo` afterwards, it will always be ignored.

What I expect: The getUserInfo always uses the  `accessToken` passed in as input, independent of the defaultHeaders.

**Comment by garg-mudit** [comment]
Hi @joaomvfsantos,
Thank you for bringing this to our attention; we will investigate and address this issue if confirmed.

**Comment by garg-mudit** [comment]
Hi @joaomvfsantos ,
A new RC version ([8.0.0-rc2](https://www.npmjs.com/package/docusign-esign/v/8.0.0-rc2)) has been released with requested fix.

Please test out the same when possible. There will be a patch version 7.0.3 will be released as well with similar fix in a day or two.

Thank You.

**Comment by joaomvfsantos** [comment]
@garg-mudit I confirm the release fixes the issue. I'm also interested in the 7.0.3 patch when it's available.

Best regards

**Comment by garg-mudit** [comment]
Hi @joaomvfsantos ,
The [7.0.3](https://www.npmjs.com/package/docusign-esign/v/7.0.3) patch version has been released. Please test it and let us know if there are any remaining issues that need resolution.

Thank You.

**Comment by joaomvfsantos** [comment]
@garg-mudit I confirm it's fixed on 7.0.3 too.
